spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample2?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
